name: Continuous Integration
on: push

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Set Node.js 16
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16"
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Set Node.js 16
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16"
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
