name: Continuous Integration
on: push

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set Node.js 14
        uses: actions/setup-node@v2.0.0
        with:
          node-version: "12"
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: yarn test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set Node.js 14
        uses: actions/setup-node@v2.0.0
        with:
          node-version: "12"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: yarn lint
